package stringer

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestRunRequiresType(t *testing.T) {
	var stderr bytes.Buffer

	err := run(nil, &stderr)
	if !errors.Is(err, errTypeRequired) {
		t.Fatalf("run error = %v, want %v", err, errTypeRequired)
	}
	if !strings.Contains(stderr.String(), "Usage of stringer:") {
		t.Fatalf("usage output missing from stderr:\n%s", stderr.String())
	}
}

func TestRunGeneratesStringerCode(t *testing.T) {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	fixture, err := os.MkdirTemp(filepath.Dir(sourceFile), ".stringer-test-")
	if err != nil {
		t.Fatalf("create fixture directory: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(fixture) })
	writeFixture(t, fixture)

	output := filepath.Join(fixture, "state_string.go")
	args := []string{
		"-type", "State",
		"-output", output,
		"-trimprefix", "State",
		"-linecomment",
		fixture,
	}
	if err := run(args, new(bytes.Buffer)); err != nil {
		t.Fatalf("run failed: %v", err)
	}

	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	content := string(generated)
	for _, want := range []string{
		"// Code generated by \"stringer -type State",
		"package fixture",
		"func (i State) String() string",
		"func StateList() []string",
		"func StateValueList() []int64",
		"func StateMap() map[string]int64",
		"func StateValueMap() map[int64]string",
		`"ready"`,
		`"done"`,
	} {
		if !strings.Contains(content, want) {
			t.Errorf("generated file missing %q:\n%s", want, content)
		}
	}
}

func writeFixture(t *testing.T, dir string) {
	t.Helper()

	content := []byte(`package fixture

type State int

const (
	StateReady State = iota // ready
	StateDone  State = 2    // done
)
`)
	if err := os.WriteFile(filepath.Join(dir, "state.go"), content, 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
}
