package stringer

import (
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/bizshuk/gosdk/service/stringer"
)

// Usage is a replacement usage function for the flags package.
func Usage() {
	_, fs := newFlagSet(os.Stderr)
	fs.Usage()
}

func printUsage(w io.Writer, fs *flag.FlagSet) {
	fmt.Fprintln(w, "Usage of stringer:")
	fmt.Fprintln(w, "\tstringer [flags] -type T [directory]")
	fmt.Fprintln(w, "\tstringer [flags] -type T files... # Must be a single package")
	fmt.Fprintln(w, "For more information, see:")
	fmt.Fprintln(w, "\thttps://pkg.go.dev/golang.org/x/tools/cmd/stringer")
	fmt.Fprintln(w, "Flags:")
	fs.SetOutput(w)
	fs.PrintDefaults()
}

type options struct {
	typeNames   string
	output      string
	trimprefix  string
	linecomment bool
	buildTags   string
}

var errTypeRequired = errors.New("-type option must be set")

func newFlagSet(stderr io.Writer) (*options, *flag.FlagSet) {
	opts := &options{}
	fs := flag.NewFlagSet("stringer", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.StringVar(&opts.typeNames, "type", "", "comma-separated list of type names; must be set")
	fs.StringVar(&opts.output, "output", "", "output file name; default srcdir/<type>_string.go")
	fs.StringVar(&opts.trimprefix, "trimprefix", "", "trim the `prefix` from the generated constant names")
	fs.BoolVar(&opts.linecomment, "linecomment", false, "use line comment text as printed text when present")
	fs.StringVar(&opts.buildTags, "tags", "", "comma-separated list of build tags to apply")
	fs.Usage = func() { printUsage(stderr, fs) }
	return opts, fs
}

func parseOptions(args []string, stderr io.Writer) (*options, *flag.FlagSet, error) {
	opts, fs := newFlagSet(stderr)
	if err := fs.Parse(args); err != nil {
		return nil, fs, err
	}
	return opts, fs, nil
}

func run(args []string, stderr io.Writer) error {
	opts, fs, err := parseOptions(args, stderr)
	if err != nil {
		return err
	}
	if opts.typeNames == "" {
		fs.Usage()
		return errTypeRequired
	}

	types := strings.Split(opts.typeNames, ",")
	var tags []string
	if opts.buildTags != "" {
		tags = strings.Split(opts.buildTags, ",")
	}

	// We accept either one directory or a list of files. Which do we have?
	patterns := fs.Args()
	if len(patterns) == 0 {
		// Default: process whole package in current directory.
		patterns = []string{"."}
	}

	// Parse the package once.
	var dir string
	g := GeneratorEx{}

	g.SetTrimPrefix(opts.trimprefix)
	g.SetLineComment(opts.linecomment)

	// TODO(suzmue): accept other patterns for packages (directories, list of files, import paths, etc).
	if len(patterns) == 1 && isDirectory(patterns[0]) {
		dir = patterns[0]
	} else {
		if len(tags) != 0 {
			return errors.New("-tags option applies only to directories, not when files are specified")
		}
		dir = filepath.Dir(patterns[0])
	}

	g.ParsePackage(patterns, tags)

	// Print the header and package clause.
	g.Printf("// Code generated by \"stringer %s\"; DO NOT EDIT.\n", strings.Join(args, " "))
	g.Printf("\n")
	g.Printf("package %s", g.GetPackage().GetName())
	g.Printf("\n")
	g.Printf("import \"strconv\"\n") // Used by all methods.

	// Run generate for each type.
	for _, typeName := range types {
		g.generate(typeName)
	}

	// Format the output.
	src := g.Format()

	// Write to file.
	outputName := opts.output
	if outputName == "" {
		baseName := fmt.Sprintf("%s_string.go", types[0])
		outputName = filepath.Join(dir, strings.ToLower(baseName))
	}
	if err := os.WriteFile(outputName, src, 0o644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}
	return nil
}

func isDirectory(name string) bool {
	info, err := os.Stat(name)
	if err != nil {
		log.Fatal(err)
	}
	return info.IsDir()
}

type GeneratorEx struct {
	stringer.Generator
}

func (g *GeneratorEx) generate(typeName string) {
	g.Generator.Generate(typeName)

	values := make([]stringer.Value, 0, 100)
	for _, file := range g.GetPackage().GetFile() {
		// Set the state for this run of the walker.
		file.SetTypeName(typeName)
		file.SetValues(nil)
		if file.GetFile() != nil {
			ast.Inspect(file.GetFile(), file.GenDecl)
			values = append(values, file.GetValues()...)
		}
	}
	runs := stringer.SplitIntoRuns(values)

	g.buildListFn(runs, typeName)
	g.buildValueListFn(runs, typeName)
	g.buildMapFn(runs, typeName)
	g.buildValueMapFn(runs, typeName)
}

func (g *GeneratorEx) buildListFn(runs [][]stringer.Value, typeName string) {
	g.Printf("\n")
	g.Printf("var _%s_list = []string{\n", typeName)
	for _, run := range runs {
		for i := range run {
			g.Printf("\t\"%s\",\n", run[i].Name())
		}
	}
	g.Printf("}\n")
	g.Printf(LIST_FN_TEMPLATE, typeName)
}

// Argument to format is the type name.
const LIST_FN_TEMPLATE = `func %[1]sList() []string {
	return _%[1]s_list
}
`

func (g *GeneratorEx) buildValueListFn(runs [][]stringer.Value, typeName string) {
	g.Printf("\n")
	g.Printf("var _%s_value_list = []int64{\n", typeName)

	for _, run := range runs {
		for i := range run {
			g.Printf("\t%d,\n", run[i].Value())
		}
	}

	g.Printf("}\n")
	g.Printf(VALUE_LIST_FN_TEMPLATE, typeName)
}

// Argument to format is the type name.
const VALUE_LIST_FN_TEMPLATE = `func %[1]sValueList() []int64 {
	return _%[1]s_value_list
}
`

func (g *GeneratorEx) buildMapFn(runs [][]stringer.Value, typeName string) {
	g.Printf("\n")
	g.Printf("var _%s_map = map[string]int64{\n", typeName)
	for _, run := range runs {
		for i := range run {
			g.Printf("\t\"%s\": %d,\n", run[i].Name(), run[i].Value())
		}
	}
	g.Printf("}\n")
	g.Printf(MAP_FN_TEMPLATE, typeName)
}

// Argument to format is the type name.
const MAP_FN_TEMPLATE = `func %[1]sMap() map[string]int64 {
	return _%[1]s_map
}
`

func (g *GeneratorEx) buildValueMapFn(runs [][]stringer.Value, typeName string) {
	g.Printf("\n")
	g.Printf("var _%s_value_map = map[int64]string{\n", typeName)
	for _, run := range runs {
		for i := range run {
			g.Printf("\t%d: \"%s\",\n", run[i].Value(), run[i].Name())
		}
	}
	g.Printf("}\n")
	g.Printf(VALUE_MAP_FN_TEMPLATE, typeName)
}

// Argument to format is the type name.
const VALUE_MAP_FN_TEMPLATE = `func %[1]sValueMap() map[int64]string {
	return _%[1]s_value_map
}
`
